modLoader="javafml"
loaderVersion="[${forgeMajor},)"
license="All rights reserved"
[[mods]]
	modId="${modId}"
	version="${version}"
	displayName="${modDisplayName}"
	logoFile="logo.png"
	updateJSONURL="${updateURL}"
	issueTrackerURL="${issuesURL}"
	displayURL="${homepageURL}"
	authors="${author}"
	description='''${modDescription}'''
[[dependencies.${modId}]]
    modId="forge"
    mandatory=true
    versionRange="[${forgeMajor},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${modId}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mcVersion}]"
    ordering="NONE"
    side="BOTH"
[[dependencies.${modId}]]
    modId="mrplibrary"
    mandatory=true
    versionRange="[${mrpLibAPI},${mrpLibNextAPI})"
    ordering="AFTER"
    side="BOTH"
